services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 300s
      timeout: 10s
      retries: 3

  redis:
    image: redis:8.6.0-alpine3.23
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
      timeout: 5s
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  data-redis:
